
# config/_default/languagues.zh.toml

languageCode = "zh"
languageName = "Chinese-Simplified"
weight = 1

title = "一切顺利鸭"
copyright = "&copy; 2025 luckya contributors"

[params]
  displayName = "ZH"
  htmlCode = "zh"
  rtl = false

# Language-specific parameters go here
[params.author]
  name = "linhao"
  image = "/img/author.jpeg"
  headline = "Everything goes well!"
  bio = "In case I don't see ya, good afternoon, good evening, and good night!"
  links = [
    { email = "linhaocoder@foxmail.com" },
    { github = "https://github.com/CornCarrots" },
  ]