[[main]]
  name = "主页"
  url = "/"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 20

# [[main]]
#  name = "分类"
#  pageRef = "categories"
#  weight = 30

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "个人简介"
  pageRef = "about"
  weight = 40

[[main]]
  identifier = "搜索"
  weight = 50
  [main.params]
    action = "search"

[[main]]
  identifier = "语言"
  weight = 100
  [main.params]
    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "标签"
#   pageRef = "tags"
#   weight = 10
